$file = 'lib\pages\new_pages\chat\chat_room_page.dart'
$content = Get-Content $file -Raw -Encoding UTF8

# S15 FIX: Ajouter un cache pour les noms des expediteurs dans les groupes
# Ajouter apres "int _messageLimit = 50;"
$old_limit = "  // Pagination des messages`r`n  int _messageLimit = 50;"
$new_limit = "  // Pagination des messages`r`n  int _messageLimit = 50;`r`n`r`n  // S15 FIX: cache noms expediteurs pour les messages de groupe`r`n  final Map<String, String> _senderNameCache = {};`r`n`r`n  Future<String> _getSenderName(String uid) async {`r`n    if (_senderNameCache.containsKey(uid)) return _senderNameCache[uid]!;`r`n    try {`r`n      final doc = await FirebaseFirestore.instance.collection('users').doc(uid).get();`r`n      if (doc.exists) {`r`n        final data = doc.data()!;`r`n        final name = data['first_name'] as String? ?? data['display_name'] as String? ?? 'Utilisateur';`r`n        _senderNameCache[uid] = name;`r`n        return name;`r`n      }`r`n    } catch (_) {}`r`n    _senderNameCache[uid] = 'Utilisateur';`r`n    return 'Utilisateur';`r`n  }"
$content = $content.Replace($old_limit, $new_limit)

# S11 FIX: rendre le header du chat cliquable pour acceder au profil
# Trouver "Expanded(" dans le header (sous le nom)
# On wrappe l'avatar + Expanded dans un GestureDetector
$old_header_row = "          Expanded(`r`n            child: Column(`r`n              crossAxisAlignment: CrossAxisAlignment.start,`r`n              children: [`r`n                Text(`r`n                  displayName,"
$new_header_row = "          // S11 FIX: tapper sur avatar/nom pour acceder au profil de l'interlocuteur`r`n          Expanded(`r`n            child: GestureDetector(`r`n              onTap: !isGroup && _otherUserData != null ? () {`r`n                final participants = List<String>.from(_effectiveChatData?['participants'] ?? []);`r`n                final currentUid = FirebaseAuth.instance.currentUser?.uid;`r`n                final otherUid = participants.firstWhere((id) => id != currentUid, orElse: () => '');`r`n                if (otherUid.isNotEmpty) context.push('/public-profile/`$otherUid');`r`n              } : null,`r`n              child: Column(`r`n              crossAxisAlignment: CrossAxisAlignment.start,`r`n              children: [`r`n                Text(`r`n                  displayName,"
$content = $content.Replace($old_header_row, $new_header_row)

# Fermer le GestureDetector dans le header (apres "Expanded(child: Column(" dans le header)
# On cherche la fin du Column des infos dans le header
$old_header_end = "                if (isGroup)`r`n                  Text(`r`n                    '`${(_effectiveChatData?['participants'] as List?)?.length ?? 0} participants',`r`n                    style: GoogleFonts.poppins(`r`n                      fontSize: 12,`r`n                      color: Colors.white.withOpacity(0.6),`r`n                    ),`r`n                  ),`r`n              ],`r`n            ),`r`n          ),"
$new_header_end = "                if (isGroup)`r`n                  Text(`r`n                    '`${(_effectiveChatData?['participants'] as List?)?.length ?? 0} participants',`r`n                    style: GoogleFonts.poppins(`r`n                      fontSize: 12,`r`n                      color: Colors.white.withOpacity(0.6),`r`n                    ),`r`n                  )`r`n                else`r`n                  // S3 FIX: afficher la presence en ligne dans le chat`r`n                  StreamBuilder<DocumentSnapshot>(`r`n                    stream: (() {`r`n                      final participants = List<String>.from(_effectiveChatData?['participants'] ?? []);`r`n                      final currentUid = FirebaseAuth.instance.currentUser?.uid;`r`n                      final otherUid = participants.firstWhere((id) => id != currentUid, orElse: () => '');`r`n                      if (otherUid.isEmpty) return const Stream.empty();`r`n                      return FirebaseFirestore.instance.collection('users').doc(otherUid).snapshots();`r`n                    })(),`r`n                    builder: (ctx, snap) {`r`n                      if (!snap.hasData || !snap.data!.exists) return const SizedBox.shrink();`r`n                      final data = snap.data!.data() as Map<String, dynamic>? ?? {};`r`n                      final isOnline = data['isOnline'] == true;`r`n                      final lastSeen = data['lastSeen'] as Timestamp?;`r`n                      String statusText = '';`r`n                      if (isOnline) {`r`n                        statusText = 'En ligne';`r`n                      } else if (lastSeen != null) {`r`n                        final diff = DateTime.now().difference(lastSeen.toDate());`r`n                        if (diff.inMinutes < 1) statusText = 'Vu a l instant';`r`n                        else if (diff.inMinutes < 60) statusText = 'Vu il y a `${diff.inMinutes} min';`r`n                        else if (diff.inHours < 24) statusText = 'Vu il y a `${diff.inHours}h';`r`n                      }`r`n                      if (statusText.isEmpty) return const SizedBox.shrink();`r`n                      return Row(`r`n                        children: [`r`n                          if (isOnline) Container(`r`n                            width: 7, height: 7,`r`n                            decoration: const BoxDecoration(color: Color(0xFF10B981), shape: BoxShape.circle),`r`n                          ),`r`n                          if (isOnline) const SizedBox(width: 4),`r`n                          Text(statusText, style: GoogleFonts.poppins(fontSize: 11, color: isOnline ? const Color(0xFF10B981) : Colors.white38)),`r`n                        ],`r`n                      );`r`n                    },`r`n                  ),`r`n              ],`r`n              ),`r`n            ),`r`n          ),"
$content = $content.Replace($old_header_end, $new_header_end)

Set-Content $file $content -Encoding UTF8
Write-Host "S3+S11+S15 fixed"
