$file = 'lib\pages\new_pages\chat\chat_room_page.dart'
$content = Get-Content $file -Raw -Encoding UTF8

# S5 FIX: _sendTypedMessage doit aussi incrementer unreadCount
$old = "      await FirebaseFirestore.instance.collection('chats').doc(widget.chatId).update({`r`n        'lastMessage': previewText,`r`n        'lastMessageTime': FieldValue.serverTimestamp(),`r`n      });"
$new = "      // S5 FIX: incrementer unreadCount pour les autres participants (partage produit/wishlist)`r`n      final chatDataForTyped = _effectiveChatData;`r`n      final participantsForTyped = List<String>.from(chatDataForTyped?['participants'] ?? []);`r`n      final Map<String, dynamic> typedUpdate = {`r`n        'lastMessage': previewText,`r`n        'lastMessageTime': FieldValue.serverTimestamp(),`r`n      };`r`n      for (final pid in participantsForTyped) {`r`n        if (pid != currentUser.uid) {`r`n          typedUpdate['unreadCount.`$pid'] = FieldValue.increment(1);`r`n        }`r`n      }`r`n      await FirebaseFirestore.instance.collection('chats').doc(widget.chatId).update(typedUpdate);"
$content = $content.Replace($old, $new)

# S14 FIX: CTA dans chat vide
$old14 = "        if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {`r`n          return Center(`r`n            child: Text(`r`n              'Aucun message',`r`n              style: GoogleFonts.poppins(color: Colors.white.withOpacity(0.5)),`r`n            ),`r`n          );`r`n        }"
$new14 = "        if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {`r`n          // S14 FIX: CTA pour le premier message`r`n          final chatData = _effectiveChatData;`r`n          final isGroup = chatData?['isGroup'] == true;`r`n          final otherName = !isGroup && _otherUserData != null`r`n              ? ((_otherUserData!['first_name'] as String?) ?? (_otherUserData!['display_name'] as String?) ?? 'votre ami')`r`n              : (chatData?['name'] as String? ?? 'le groupe');`r`n          return Center(`r`n            child: Column(`r`n              mainAxisAlignment: MainAxisAlignment.center,`r`n              children: [`r`n                Container(`r`n                  padding: const EdgeInsets.all(20),`r`n                  decoration: BoxDecoration(`r`n                    shape: BoxShape.circle,`r`n                    color: const Color(0xFF8A2BE2).withOpacity(0.15),`r`n                  ),`r`n                  child: const Icon(Icons.waving_hand_rounded, size: 48, color: Color(0xFF8A2BE2)),`r`n                ),`r`n                const SizedBox(height: 16),`r`n                Text(`r`n                  'Dites bonjour a `$otherName !',`r`n                  style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w600, color: Colors.white),`r`n                  textAlign: TextAlign.center,`r`n                ),`r`n                const SizedBox(height: 8),`r`n                Text(`r`n                  'Envoyez votre premier message',`r`n                  style: GoogleFonts.poppins(fontSize: 14, color: Colors.white38),`r`n                ),`r`n              ],`r`n            ),`r`n          );`r`n        }"
$content = $content.Replace($old14, $new14)

Set-Content $file $content -Encoding UTF8
Write-Host "S5+S14 fixed"
