const fs=require('fs');
const files=['lib/pages/new_pages/gift_results/gift_results_widget.dart','lib/pages/new_pages/home_pinterest/home_pinterest_widget.dart','lib/pages/new_pages/search_page/search_page_widget.dart','lib/pages/new_pages/user_profile/user_profile_widget.dart'];

const dict = {
    'G\uFFFDn\uFFFDration': 'Génération',
    'r\uFFFDsum\uFFFD': 'résumé',
    'personnalis\uFFFD': 'personnalisé',
    'R\uFFFDsultats': 'Résultats',
    'trouv\uFFFDs': 'trouvés',
    'S\uFFFDlectionn\uFFFDs': 'Sélectionnés',
    's\uFFFDcuris\uFFFD': 'sécurisé',
    '\uFFFDviter': 'éviter',
    '}': '}€',
    '0': '0€',
    'G\uFFFDn\uFFFDrer': 'Générer',
    'pr\uFFFDcision': 'précision',
    'connect\uFFFD': 'connecté',
    'charg\uFFFDs': 'chargés',
    'cr\uFFFDer': 'créer',
    'popularit\uFFFD': 'popularité',
    'sp\uFFFDcifique': 'spécifique',
    'requ\uFFFDte': 'requête',
    'n\uFFFDcessite': 'nécessite',
    'Augment\uFFFD': 'Augmenté',
    'R\uFFFDinitialiser': 'Réinitialiser',
    'm\uFFFDme': 'même',
    'g\uFFFDre': 'gère',
    '\uFFFDa': 'ça',
    'utilis\uFFFDs': 'utilisés',
    'th\uFFFDmatiques': 'thématiques',
    'd\uFFFDj\uFFFD': 'déjà',
    'cat\uFFFDgorie': 'catégorie',
    'd\uFFFDterminer': 'déterminer',
    'Am\uFFFDlioration': 'Amélioration',
    'r\uFFFDcup\uFFFDrer': 'récupérer',
    'imm\uFFFDdiatement': 'immédiatement',
    'APR\uFFFDs': 'APRÈS',
    'v\uFFFDtement': 'vêtement',
    'd\uFFFDco': 'déco',
    'beaut\uFFFD': 'beauté',
    'cosm\uFFFDtique': 'cosmétique',
    'bien-\uFFFDtre': 'bien-être',
    'cr\uFFFDatif': 'créatif',
    'd\uFFFDfaut': 'défaut',
    'succ\uFFFDs': 'succès',
    'Id\uFFFDes': 'Idées',
    'D\uFFFDcouvre': 'Découvre',
    'd\uFFFDcouverte': 'découverte',
    's\uFFFDlection': 'sélection',
    'diff\uFFFDrencier': 'différencier',
    'fl\uFFFDche': 'flèche',
    'c\uFFFDur': 'cœur',
    'rafra\uFFFDchissement': 'rafraîchissement',
    'apr\uFFFDs': 'après',
    'Cr\uFFFDe': 'Crée',
    'd\uFFFDtails': 'détails',
    'r\uFFFDussite': 'réussite',
    's\uFFFDlectionne': 'sélectionne',
    'sauvegard\uFFFDs': 'sauvegardés',
    's\uFFFDlectionn\uFFFD': 'sélectionné',
    'supprim\uFFFD': 'supprimé',
    'premi\uFFFDre': 'première',
    'g\uFFFDn\uFFFDrer': 'générer',
    'appara\uFFFDtront': 'apparaîtront',
    'hi\uFFFDrarchie': 'hiérarchie',
    'ajout\uFFFD': 'ajouté',
    'd\uFFFDsactiv\uFFFDes': 'désactivées',
    'cat\uFFFDgories': 'catégories',
    'r\uFFFDsultats': 'résultats',
    'D\uFFFDterminer': 'Déterminer',
    'V\uFFFDrifie': 'Vérifie',

    'V+\uFFFDrifier': 'Vérifier',
    'apr+\uFFFDs': 'après',
    '+\uFFFDcouter': 'Écouter',
    'param+\uFFFDtres': 'paramètres',
    'flout+\uFFFD': 'flouté',
    'Cr+\uFFFDe': 'Crée',
    'acc+\uFFFDder': 'accéder',
    'lik+\uFFFDs': 'likés',
    'lik+\uFFFD': 'liké',
    'pr+\uFFFDf+\uFFFDr+\uFFFDs': 'préférés',
    '+\uFFFD': 'à',

    '\uFFFDviter': 'éviter',
    'pr\uFFFDm': 'prénom',
    'r\uFFFDcup': 'récup',
    'r\uFFFDini': 'réini',
    'D\uFFFDj\uFFFD': 'Déjà',
    '\uFFFDtre': 'être',
    'r\uFFFDessaye': 'réessaye',
    '\uFFFDC': 'É',
    ' \uFFFD ': ' à ',
    '(\uFFFD ': '(à ',
    '\uFFFD': 'é' 
};

files.forEach(f=>{
    let c = fs.readFileSync(f,'utf8');
    for(let k in dict) {
        c = c.split(k).join(dict[k]);
    }
    fs.writeFileSync(f, c);
});
console.log('Done!');
