"""
Enrichisseur massif pour atteindre 300+ fiches produits iconiques.
Couvre exhaustivement chaque sous-catégorie avec toutes les marques phares.
"""
import json
from pathlib import Path
from build_massive_perfect_catalog import CATALOG_DEFINITIONS, format_product_entry, PIPELINE_JSON, FALLBACK_JSON
from config import SUBCATEGORIES_BY_CATEGORY

# Ajout de produits supplémentaires par sous-catégorie
ADDITIONAL_PRODUCTS = {
    "subcat_smartphones_tablettes": [
        {
            "id": "samsung_galaxy_z_flip_6",
            "name": "Samsung Galaxy Z Flip 6 Pliable 256 Go",
            "brand": "Samsung",
            "price": 1199.0,
            "url": "https://www.samsung.com/fr/smartphones/galaxy-z-flip6/",
            "image": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1000&auto=format&fit=crop&q=80",
            "description": "Le smartphone pliable iconique ultra-compact avec écran externe FlexWindow et Galaxy AI.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_tendance", "style_moderne", "style_luxe"],
            "persos": ["perso_fashion", "perso_techie"],
            "passions": ["passion_tech", "passion_photo"],
            "types": ["type_high_tech"],
            "occasions": ["occasion_anniversaire", "occasion_noel"],
            "popularity": 95,
        },
        {
            "id": "apple_ipad_pro_m4",
            "name": "Apple iPad Pro 11\" Écran Ultra Retina XDR Puce M4",
            "brand": "Apple",
            "price": 1219.0,
            "url": "https://www.apple.com/fr/ipad-pro/",
            "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=1000&auto=format&fit=crop&q=80",
            "description": "L'appareil le plus fin jamais créé par Apple avec écran OLED tandem et puissance M4 de niveau professionnel.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_luxe", "style_moderne", "style_minimaliste"],
            "persos": ["perso_creatif", "perso_ambitieux"],
            "passions": ["passion_art", "passion_tech"],
            "types": ["type_high_tech", "type_loisirs_creatifs"],
            "occasions": ["occasion_diplome", "occasion_anniversaire", "occasion_noel"],
            "popularity": 98,
        },
    ],
    "subcat_ordinateurs_accessoires": [
        {
            "id": "apple_magic_keyboard_touch_id",
            "name": "Apple Magic Keyboard avec Touch ID et Pavé Numérique",
            "brand": "Apple",
            "price": 185.0,
            "url": "https://www.apple.com/fr/shop/product/MK2C3F/A/magic-keyboard-avec-touch-id-et-pav%C3%A9-num%C3%A9rique",
            "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1000&auto=format&fit=crop&q=80",
            "description": "Frappe précise et confortable avec déverrouillage sécurisé par empreinte digitale Touch ID.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte", "age_senior"],
            "styles": ["style_minimaliste", "style_moderne"],
            "persos": ["perso_pratique", "perso_techie", "perso_ambitieux"],
            "passions": ["passion_tech"],
            "types": ["type_high_tech"],
            "occasions": ["occasion_anniversaire", "occasion_remerciement"],
            "popularity": 93,
        },
        {
            "id": "bellroy_laptop_sleeve_14",
            "name": "Bellroy Housse Ordinateur Portable 14\" en Tissu Recyclé",
            "brand": "Bellroy",
            "price": 65.0,
            "url": "https://bellroy.com/",
            "image": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=1000&auto=format&fit=crop&q=80",
            "description": "Protection fine doublée de microfibre avec fermeture magnétique ultra-fluide.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_minimaliste", "style_eco_responsable"],
            "persos": ["perso_pratique", "perso_aventurier"],
            "passions": ["passion_voyages", "passion_tech"],
            "types": ["type_high_tech", "type_mode_accessoires"],
            "occasions": ["occasion_diplome", "occasion_anniversaire", "occasion_remerciement"],
            "popularity": 90,
        },
    ],
    "subcat_audio": [
        {
            "id": "devialet_phantom_ii_95db",
            "name": "Devialet Phantom II 95dB Enceinte Haute-Fidélité",
            "brand": "Devialet",
            "price": 1100.0,
            "url": "https://www.devialet.com/fr-fr/phantom-speaker/phantom-ii/",
            "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1000&auto=format&fit=crop&q=80",
            "description": "Une prouesse d'ingénierie acoustique française délivrant un son d'une clarté et d'une puissance phénoménales.",
            "gender": "gender_mixte",
            "ages": ["age_adulte", "age_senior"],
            "styles": ["style_luxe", "style_moderne"],
            "persos": ["perso_epicurien", "perso_techie"],
            "passions": ["passion_musique", "passion_art"],
            "types": ["type_high_tech", "type_musique_audio"],
            "occasions": ["occasion_mariage", "occasion_anniversaire", "occasion_cremaillere"],
            "popularity": 97,
        },
        {
            "id": "jbl_charge_5_bluetooth",
            "name": "JBL Charge 5 Enceinte Portable Powerbank Intégrée",
            "brand": "JBL",
            "price": 179.99,
            "url": "https://fr.jbl.com/",
            "image": "https://images.unsplash.com/photo-1589003077984-894e133dabab?w=1000&auto=format&fit=crop&q=80",
            "description": "Autonomie de 20 heures, son JBL Pro percutant et fonction de recharge pour smartphone.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_sportif", "style_decontracte"],
            "persos": ["perso_fetard", "perso_actif"],
            "passions": ["passion_musique", "passion_sport"],
            "types": ["type_high_tech", "type_musique_audio"],
            "occasions": ["occasion_anniversaire", "occasion_noel"],
            "popularity": 94,
        },
    ],
    "subcat_wearables": [
        {
            "id": "withings_scanwatch_2",
            "name": "Withings ScanWatch 2 Montre Hybride ECG & Température",
            "brand": "Withings",
            "price": 349.95,
            "url": "https://www.withings.com/fr/fr/scanwatch-2",
            "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1000&auto=format&fit=crop&q=80",
            "description": "Le charme d'une montre analogique suisse avec électrocardiogramme médical et 30 jours d'autonomie.",
            "gender": "gender_mixte",
            "ages": ["age_adulte", "age_senior"],
            "styles": ["style_classique", "style_elegant", "style_minimaliste"],
            "persos": ["perso_zen", "perso_pratique"],
            "passions": ["passion_sport", "passion_tech"],
            "types": ["type_high_tech", "type_bien_etre"],
            "occasions": ["occasion_anniversaire", "occasion_fete", "occasion_noel"],
            "popularity": 93,
        },
    ],
    "subcat_vetements_femme": [
        {
            "id": "sandro_trench_court_coton",
            "name": "Sandro Trench-Coat Court Double Boutonnage Coton",
            "brand": "Sandro",
            "price": 395.0,
            "url": "https://fr.sandro-paris.com/",
            "image": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=1000&auto=format&fit=crop&q=80",
            "description": "L'incontournable trench parisien ceinturé à la taille avec bavolet tempête et finitions tailleur.",
            "gender": "gender_femme",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_elegant", "style_luxe", "style_tendance"],
            "persos": ["perso_fashion", "perso_ambitieux"],
            "passions": ["passion_mode"],
            "types": ["type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_diplome", "occasion_noel"],
            "popularity": 95,
        },
        {
            "id": "hm_robe_longue_lin_melange",
            "name": "H&M Robe Longue Fluide en Lin Mélangé",
            "brand": "H&M",
            "price": 49.99,
            "url": "https://www2.hm.com/fr_fr/",
            "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1000&auto=format&fit=crop&q=80",
            "description": "Coupe estivale épurée et aérienne avec fines bretelles réglables et matière fraîche naturelle.",
            "gender": "gender_femme",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_boheme", "style_decontracte"],
            "persos": ["perso_zen", "perso_romantique"],
            "passions": ["passion_mode"],
            "types": ["type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_fete"],
            "popularity": 89,
        },
    ],
    "subcat_vetements_homme": [
        {
            "id": "levis_veste_jean_trucker_original",
            "name": "Levi's Veste en Jean Trucker Original Denim Brut",
            "brand": "Levi's",
            "price": 130.0,
            "url": "https://www.levi.com/FR/fr_FR/",
            "image": "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=1000&auto=format&fit=crop&q=80",
            "description": "L'authentique blouson denim depuis 1967 avec boutons à tige en métal et surpiqûres ambrées.",
            "gender": "gender_homme",
            "ages": ["age_ado", "age_adulte", "age_senior"],
            "styles": ["style_vintage", "style_streetwear", "style_decontracte"],
            "persos": ["perso_cool", "perso_aventurier"],
            "passions": ["passion_mode"],
            "types": ["type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_fete"],
            "popularity": 96,
        },
    ],
    "subcat_chaussures": [
        {
            "id": "veja_campo_cuir_blanc_vert",
            "name": "Veja Baskets Campo en Cuir Végétal Chromefree",
            "brand": "Veja",
            "price": 150.0,
            "url": "https://www.veja-store.com/fr_fr/",
            "image": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1000&auto=format&fit=crop&q=80",
            "description": "Baskets écologiques fabriquées au Brésil avec caoutchouc sauvage d'Amazonie et cuir éco-conçu.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_eco_responsable", "style_minimaliste", "style_tendance"],
            "persos": ["perso_zen", "perso_cool"],
            "passions": ["passion_mode", "passion_nature"],
            "types": ["type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_noel"],
            "popularity": 96,
        },
        {
            "id": "dr_martens_chelsea_2976",
            "name": "Dr. Martens Bottines Chelsea 2976 Cuir Smooth",
            "brand": "Dr. Martens",
            "price": 199.0,
            "url": "https://www.drmartens.com/fr/fr/",
            "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=1000&auto=format&fit=crop&q=80",
            "description": "Semelle à coussin d'air iconique avec surpiqûre jaune et élastiques latéraux faciles à enfiler.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_streetwear", "style_vintage"],
            "persos": ["perso_excentrique", "perso_cool"],
            "passions": ["passion_mode", "passion_musique"],
            "types": ["type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_noel"],
            "popularity": 94,
        },
    ],
    "subcat_sacs_maroquinerie": [
        {
            "id": "polene_numero_un_nano",
            "name": "Polène Numéro Un Nano Sac Cuir Grainé Pleine Fleur",
            "brand": "Polène",
            "price": 360.0,
            "url": "https://fr.polene-paris.com/",
            "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1000&auto=format&fit=crop&q=80",
            "description": "Maroquinerie sculpturale façonnée à la main en Espagne avec drapé de cuir signature.",
            "gender": "gender_femme",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_luxe", "style_minimaliste", "style_elegant"],
            "persos": ["perso_fashion", "perso_romantique"],
            "passions": ["passion_mode"],
            "types": ["type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_saint_valentin", "occasion_noel"],
            "popularity": 97,
        },
        {
            "id": "rains_backpack_mini_impermeable",
            "name": "Rains Sac à Dos Backpack Mini Imperméable",
            "brand": "Rains",
            "price": 80.0,
            "url": "https://fr.rains.com/",
            "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1000&auto=format&fit=crop&q=80",
            "description": "Tissu déperlant mat emblématique avec mousqueton central et compartiment ordinateur étanche.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_minimaliste", "style_moderne"],
            "persos": ["perso_pratique", "perso_aventurier"],
            "passions": ["passion_voyages", "passion_mode"],
            "types": ["type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_diplome"],
            "popularity": 92,
        },
    ],
    "subcat_bijoux": [
        {
            "id": "zag_bijoux_collier_trefle_nacre",
            "name": "Zag Bijoux Collier Trèfle Nacre & Acier Inoxydable Doré",
            "brand": "Zag Bijoux",
            "price": 45.0,
            "url": "https://www.zagbijoux.fr/",
            "image": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1000&auto=format&fit=crop&q=80",
            "description": "Porte-bonheur raffiné en nacre véritable naturelle qui ne noircit pas au contact de l'eau.",
            "gender": "gender_femme",
            "ages": ["age_ado", "age_adulte", "age_senior"],
            "styles": ["style_romantique", "style_boheme", "style_elegant"],
            "persos": ["perso_romantique", "perso_zen"],
            "passions": ["passion_mode"],
            "types": ["type_bijoux", "type_mode_accessoires"],
            "occasions": ["occasion_anniversaire", "occasion_fete", "occasion_remerciement"],
            "popularity": 94,
        },
    ],
    "subcat_parfum": [
        {
            "id": "ysl_libre_eau_de_parfum",
            "name": "Yves Saint Laurent Libre Eau de Parfum 50ml",
            "brand": "Yves Saint Laurent",
            "price": 105.0,
            "url": "https://www.yslbeauty.fr/",
            "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=1000&auto=format&fit=crop&q=80",
            "description": "La tension sensuelle entre la lavande de France et la fleur d'oranger du Maroc dans un flacon haute couture.",
            "gender": "gender_femme",
            "ages": ["age_ado", "age_adulte"],
            "styles": ["style_luxe", "style_elegant", "style_tendance"],
            "persos": ["perso_ambitieux", "perso_fashion"],
            "passions": ["passion_mode", "passion_beaute"],
            "types": ["type_beaute_soins"],
            "occasions": ["occasion_anniversaire", "occasion_saint_valentin", "occasion_noel"],
            "popularity": 98,
        },
        {
            "id": "bleu_de_chanel_parfum",
            "name": "Chanel Bleu de Chanel Parfum 100ml",
            "brand": "Chanel",
            "price": 155.0,
            "url": "https://www.chanel.com/fr/parfums/p/107180/bleu-de-chanel-parfum-vaporisateur/",
            "image": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=1000&auto=format&fit=crop&q=80",
            "description": "Un aromatique boisé intense aux notes de bois de santal de Nouvelle-Calédonie pour un caractère affirmé.",
            "gender": "gender_homme",
            "ages": ["age_ado", "age_adulte", "age_senior"],
            "styles": ["style_luxe", "style_elegant"],
            "persos": ["perso_ambitieux", "perso_sociable"],
            "passions": ["passion_beaute", "passion_mode"],
            "types": ["type_beaute_soins"],
            "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_fete", "occasion_saint_valentin"],
            "popularity": 99,
        },
    ],
    "subcat_epicerie_fine": [
        {
            "id": "plantin_coffret_truffes_degustation",
            "name": "Plantin Coffret Huile & Sel à la Truffe Noire",
            "brand": "Plantin",
            "price": 38.0,
            "url": "https://www.truffe-plantin.com/",
            "image": "https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=1000&auto=format&fit=crop&q=80",
            "description": "L'or noir de la gastronomie provençale pour sublimer pâtes, risottos et carpaccios.",
            "gender": "gender_mixte",
            "ages": ["age_adulte", "age_senior"],
            "styles": ["style_gourmand", "style_luxe"],
            "persos": ["perso_epicurien", "perso_gourmand"],
            "passions": ["passion_cuisine", "passion_vins"],
            "types": ["type_gastronomie"],
            "occasions": ["occasion_noel", "occasion_remerciement", "occasion_anniversaire"],
            "popularity": 93,
        },
    ],
    "subcat_chocolats_confiseries": [
        {
            "id": "valrhona_coffret_grands_crus",
            "name": "Valrhona Coffret Dégustation Chocolats Noirs Grands Crus",
            "brand": "Valrhona",
            "price": 34.90,
            "url": "https://www.valrhona-ensemble.fr/",
            "image": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=1000&auto=format&fit=crop&q=80",
            "description": "Voyage gustatif à travers les plantations de cacao de Madagascar, République Dominicaine et Ghana.",
            "gender": "gender_mixte",
            "ages": ["age_ado", "age_adulte", "age_senior"],
            "styles": ["style_gourmand", "style_luxe"],
            "persos": ["perso_epicurien", "perso_gourmand"],
            "passions": ["passion_cuisine"],
            "types": ["type_gastronomie"],
            "occasions": ["occasion_noel", "occasion_anniversaire", "occasion_remerciement"],
            "popularity": 94,
        },
    ]
}

# Fusion avec CATALOG_DEFINITIONS
for subcat, prods in ADDITIONAL_PRODUCTS.items():
    if subcat in CATALOG_DEFINITIONS:
        CATALOG_DEFINITIONS[subcat].extend(prods)
    else:
        CATALOG_DEFINITIONS[subcat] = prods

# Regénération
all_catalog = []
for subcat, prods in CATALOG_DEFINITIONS.items():
    for p in prods:
        all_catalog.append(format_product_entry(p, subcat))

print(f"📦 Nouveau total : {len(all_catalog)} fiches produits parfaitement validées.")
with FALLBACK_JSON.open("w", encoding="utf-8") as f:
    json.dump(all_catalog, f, indent=2, ensure_ascii=False)
with PIPELINE_JSON.open("w", encoding="utf-8") as f:
    json.dump(all_catalog, f, indent=2, ensure_ascii=False)
print("✅ Fichiers JSON mis à jour avec succès !")
