"""
Générateur du catalogue exhaustif et parfait pour DORÕN.
Couvre 100% des 5 catégories, 35 sous-catégories, 30+ marques majeures,
toutes les tranches de prix, âges, genres, styles et personnalités.
Valide 100% des tags contre TagsDefinitions.
"""

import json
import os
import re
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
FALLBACK_JSON = BASE_DIR / "assets" / "jsons" / "fallback_products.json"
PIPELINE_JSON = BASE_DIR / "scripts" / "pipeline" / "final_doron_catalog.json"

PRODUCTS_DATA = [
    # =========================================================================
    # 1. TECH (cat_tech)
    # =========================================================================
    # 1.1 subcat_smartphones_tablettes
    {
        "id": "apple_iphone_16_pro",
        "name": "Apple iPhone 16 Pro 128 Go",
        "brand": "Apple",
        "price": 1229.0,
        "url": "https://www.apple.com/fr/iphone-16-pro/",
        "image": "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=1000&auto=format&fit=crop&q=80",
        "description": "Design en titane avec bouton Action, caméra 48 Mpx et puce A18 Pro pour des performances incomparables.",
        "category": "cat_tech",
        "subcategory": "subcat_smartphones_tablettes",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_moderne", "style_minimaliste"],
        "persos": ["perso_techie", "perso_ambitieux"],
        "passions": ["passion_tech", "passion_photo", "passion_jeuxvideo"],
        "types": ["type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 99,
    },
    {
        "id": "samsung_galaxy_s24_ultra",
        "name": "Samsung Galaxy S24 Ultra 256 Go",
        "brand": "Samsung",
        "price": 1469.0,
        "url": "https://www.samsung.com/fr/smartphones/galaxy-s24-ultra/",
        "image": "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=1000&auto=format&fit=crop&q=80",
        "description": "Le fleuron Android avec Galaxy AI intégrée, cadre titane, stylet S-Pen et capteur 200 Mpx.",
        "category": "cat_tech",
        "subcategory": "subcat_smartphones_tablettes",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_moderne"],
        "persos": ["perso_techie", "perso_creatif"],
        "passions": ["passion_tech", "passion_photo"],
        "types": ["type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 96,
    },
    {
        "id": "apple_ipad_air_m2",
        "name": "Apple iPad Air 11\" Puce M2",
        "brand": "Apple",
        "price": 719.0,
        "url": "https://www.apple.com/fr/ipad-air/",
        "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=1000&auto=format&fit=crop&q=80",
        "description": "Écran Liquid Retina spectaculaire, puissance phénoménale de la puce M2 et compatibilité Apple Pencil Pro.",
        "category": "cat_tech",
        "subcategory": "subcat_smartphones_tablettes",
        "gender": "gender_mixte",
        "ages": ["age_enfant", "age_ado", "age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_minimaliste"],
        "persos": ["perso_creatif", "perso_intellectuel", "perso_techie"],
        "passions": ["passion_art", "passion_tech", "passion_cinema"],
        "types": ["type_high_tech", "type_loisirs_creatifs"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 94,
    },
    {
        "id": "google_pixel_8a",
        "name": "Google Pixel 8a 128 Go",
        "brand": "Google",
        "price": 499.0,
        "url": "https://store.google.com/fr/product/pixel_8a",
        "image": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1000&auto=format&fit=crop&q=80",
        "description": "L'expérience photo Google avec intelligence artificielle, puce Tensor G3 et 7 ans de mises à jour.",
        "category": "cat_tech",
        "subcategory": "subcat_smartphones_tablettes",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_decontracte"],
        "persos": ["perso_pratique", "perso_techie"],
        "passions": ["passion_tech", "passion_photo"],
        "types": ["type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 89,
    },

    # 1.2 subcat_ordinateurs_accessoires
    {
        "id": "apple_macbook_air_m3",
        "name": "Apple MacBook Air 13\" Puce M3",
        "brand": "Apple",
        "price": 1299.0,
        "url": "https://www.apple.com/fr/macbook-air/",
        "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1000&auto=format&fit=crop&q=80",
        "description": "Design ultrafin et silencieux, autonomie jusqu'à 18 heures et puissance époustouflante de la puce M3.",
        "category": "cat_tech",
        "subcategory": "subcat_ordinateurs_accessoires",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_minimaliste", "style_moderne"],
        "persos": ["perso_ambitieux", "perso_creatif", "perso_techie"],
        "passions": ["passion_tech", "passion_photo", "passion_musique"],
        "types": ["type_high_tech"],
        "occasions": ["occasion_diplome", "occasion_anniversaire", "occasion_noel"],
        "popularity": 98,
    },
    {
        "id": "logitech_mx_master_3s",
        "name": "Logitech MX Master 3S Souris Sans Fil Performance",
        "brand": "Logitech",
        "price": 129.0,
        "url": "https://www.logitech.com/fr-fr/products/mice/mx-master-3s.html",
        "image": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1000&auto=format&fit=crop&q=80",
        "description": "Précision chirurgicale sur toutes les surfaces, clics silencieux et molette MagSpeed ultra-rapide.",
        "category": "cat_tech",
        "subcategory": "subcat_ordinateurs_accessoires",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_minimaliste"],
        "persos": ["perso_pratique", "perso_techie", "perso_ambitieux"],
        "passions": ["passion_tech", "passion_jeuxvideo"],
        "types": ["type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_remerciement"],
        "popularity": 95,
    },
    {
        "id": "harber_london_leather_desk_mat",
        "name": "Harber London Sous-Main en Cuir Véritable et Feutre",
        "brand": "Harber London",
        "price": 119.0,
        "url": "https://www.harberlondon.com/",
        "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1000&auto=format&fit=crop&q=80",
        "description": "Cuir pleine fleur tanné végétal avec base en feutre de laine pour un espace de travail ultra raffiné.",
        "category": "cat_tech",
        "subcategory": "subcat_ordinateurs_accessoires",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_elegant", "style_minimaliste"],
        "persos": ["perso_ambitieux", "perso_intellectuel"],
        "passions": ["passion_tech", "passion_mode"],
        "types": ["type_high_tech", "type_maison_deco"],
        "occasions": ["occasion_anniversaire", "occasion_remerciement", "occasion_fete"],
        "popularity": 88,
    },
    {
        "id": "anker_hub_usb_c_7_en_1",
        "name": "Anker Hub USB-C 7-en-1 HDMI 4K & Power Delivery",
        "brand": "Anker",
        "price": 49.99,
        "url": "https://www.anker.com/",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1000&auto=format&fit=crop&q=80",
        "description": "Extension complète avec ports HDMI 4K, USB 3.0, lecteur SD et charge rapide 100W.",
        "category": "cat_tech",
        "subcategory": "subcat_ordinateurs_accessoires",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_moderne", "style_minimaliste"],
        "persos": ["perso_pratique", "perso_techie"],
        "passions": ["passion_tech", "passion_photo"],
        "types": ["type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 90,
    },

    # 1.3 subcat_audio
    {
        "id": "apple_airpods_pro_2_usbc",
        "name": "Apple AirPods Pro 2 (USB-C)",
        "brand": "Apple",
        "price": 279.0,
        "url": "https://www.apple.com/fr/airpods-pro/",
        "image": "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=1000&auto=format&fit=crop&q=80",
        "description": "Réduction active du bruit 2x plus efficace, audio spatial personnalisé et boîtier résistant MagSafe USB-C.",
        "category": "cat_tech",
        "subcategory": "subcat_audio",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_minimaliste", "style_luxe"],
        "persos": ["perso_techie", "perso_actif", "perso_cool"],
        "passions": ["passion_musique", "passion_sport", "passion_voyages"],
        "types": ["type_high_tech", "type_musique_audio"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 99,
    },
    {
        "id": "sony_wh_1000xm5",
        "name": "Sony WH-1000XM5 Casque Sans Fil Réduction de Bruit",
        "brand": "Sony",
        "price": 379.0,
        "url": "https://www.sony.fr/electronics/casques-bandeau/wh-1000xm5",
        "image": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1000&auto=format&fit=crop&q=80",
        "description": "La référence absolue des casques circum-auriculaires avec 8 micros antibruit et confort longue durée.",
        "category": "cat_tech",
        "subcategory": "subcat_audio",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_moderne", "style_luxe"],
        "persos": ["perso_techie", "perso_zen", "perso_intellectuel"],
        "passions": ["passion_musique", "passion_voyages", "passion_cinema"],
        "types": ["type_high_tech", "type_musique_audio"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 97,
    },
    {
        "id": "marshall_stanmore_iii",
        "name": "Marshall Stanmore III Enceinte Bluetooth Vintage",
        "brand": "Marshall",
        "price": 399.0,
        "url": "https://www.marshallheadphones.com/",
        "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1000&auto=format&fit=crop&q=80",
        "description": "Un son immersif légendaire dans un habillage vinyle iconique vintage qui habille tous les intérieurs.",
        "category": "cat_tech",
        "subcategory": "subcat_audio",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_vintage", "style_luxe", "style_tendance"],
        "persos": ["perso_cool", "perso_fetard", "perso_creatif"],
        "passions": ["passion_musique", "passion_art"],
        "types": ["type_high_tech", "type_musique_audio", "type_maison_deco"],
        "occasions": ["occasion_anniversaire", "occasion_cremaillere", "occasion_noel"],
        "popularity": 96,
    },
    {
        "id": "jbl_flip_6",
        "name": "JBL Flip 6 Enceinte Portable Étanche IP67",
        "brand": "JBL",
        "price": 119.0,
        "url": "https://fr.jbl.com/enceintes-portables/FLIP-6-.html",
        "image": "https://images.unsplash.com/photo-1589003077984-894e133dabab?w=1000&auto=format&fit=crop&q=80",
        "description": "Son puissant à 2 voies, autonomie de 12 heures et résistance totale à l'eau et à la poussière.",
        "category": "cat_tech",
        "subcategory": "subcat_audio",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_sportif", "style_decontracte"],
        "persos": ["perso_fetard", "perso_aventurier", "perso_actif"],
        "passions": ["passion_musique", "passion_sport", "passion_voyages"],
        "types": ["type_high_tech", "type_musique_audio"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 94,
    },

    # 1.4 subcat_wearables
    {
        "id": "apple_watch_series_9",
        "name": "Apple Watch Series 9 GPS 45mm",
        "brand": "Apple",
        "price": 479.0,
        "url": "https://www.apple.com/fr/apple-watch-series-9/",
        "image": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=1000&auto=format&fit=crop&q=80",
        "description": "Puce S9 ultra-rapide, geste toucher deux fois magique et capteurs de santé avancés.",
        "category": "cat_tech",
        "subcategory": "subcat_wearables",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_sportif", "style_luxe"],
        "persos": ["perso_actif", "perso_techie", "perso_ambitieux"],
        "passions": ["passion_sport", "passion_tech"],
        "types": ["type_high_tech", "type_sport_outdoor"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 98,
    },
    {
        "id": "garmin_fenix_7_pro",
        "name": "Garmin Fenix 7 Pro Sapphire Solar",
        "brand": "Garmin",
        "price": 799.0,
        "url": "https://www.garmin.com/fr-FR/p/866191",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1000&auto=format&fit=crop&q=80",
        "description": "Montre GPS multisport outdoor avec verre solaire Power Sapphire, lampe torche LED et cartographie.",
        "category": "cat_tech",
        "subcategory": "subcat_wearables",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_sportif", "style_luxe"],
        "persos": ["perso_aventurier", "perso_sportif", "perso_actif"],
        "passions": ["passion_sport", "passion_nature", "passion_voyages"],
        "types": ["type_high_tech", "type_sport_outdoor"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 93,
    },
    {
        "id": "oura_ring_gen_3",
        "name": "Oura Ring Gen 3 Bague Connectée Sommeil & Santé",
        "brand": "Oura",
        "price": 329.0,
        "url": "https://ouraring.com/fr",
        "image": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1000&auto=format&fit=crop&q=80",
        "description": "Suivi du sommeil, de la récupération et de la fréquence cardiaque au doigt dans un écrin titane minimaliste.",
        "category": "cat_tech",
        "subcategory": "subcat_wearables",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_minimaliste", "style_luxe", "style_moderne"],
        "persos": ["perso_zen", "perso_actif", "perso_techie"],
        "passions": ["passion_tech", "passion_sport", "passion_beaute"],
        "types": ["type_high_tech", "type_bien_etre"],
        "occasions": ["occasion_anniversaire", "occasion_saint_valentin", "occasion_noel"],
        "popularity": 92,
    },

    # 1.5 subcat_photo_video
    {
        "id": "polaroid_i2_instant",
        "name": "Polaroid I-2 Appareil Photo Instantané Argentique Pro",
        "brand": "Polaroid",
        "price": 699.0,
        "url": "https://www.polaroid.com/fr_fr",
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=1000&auto=format&fit=crop&q=80",
        "description": "Optique ultra-lumineuse à 3 éléments avec commandes manuelles complètes et capteur LiDAR.",
        "category": "cat_tech",
        "subcategory": "subcat_photo_video",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_vintage", "style_creatif", "style_luxe"],
        "persos": ["perso_creatif", "perso_cool", "perso_romantique"],
        "passions": ["passion_photo", "passion_art", "passion_voyages"],
        "types": ["type_high_tech", "type_culture"],
        "occasions": ["occasion_mariage", "occasion_anniversaire", "occasion_noel"],
        "popularity": 94,
    },
    {
        "id": "dji_osmo_pocket_3",
        "name": "DJI Osmo Pocket 3 Caméra Stabilisée Capteur 1 Pouce",
        "brand": "DJI",
        "price": 539.0,
        "url": "https://store.dji.com/fr/product/osmo-pocket-3",
        "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1000&auto=format&fit=crop&q=80",
        "description": "Capteur CMOS 1 pouce capable de filmer en 4K 120fps avec écran tactile pivotant et nacelle 3 axes.",
        "category": "cat_tech",
        "subcategory": "subcat_photo_video",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_moderne", "style_tech"],
        "persos": ["perso_creatif", "perso_aventurier", "perso_sociable"],
        "passions": ["passion_voyages", "passion_photo", "passion_tech"],
        "types": ["type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_diplome", "occasion_noel"],
        "popularity": 96,
    },

    # 1.6 subcat_gaming
    {
        "id": "playstation_5_slim",
        "name": "Sony PlayStation 5 Slim Édition Standard",
        "brand": "Sony",
        "price": 549.99,
        "url": "https://www.playstation.com/fr-fr/ps5/",
        "image": "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=1000&auto=format&fit=crop&q=80",
        "description": "Graphismes 4K jusqu'à 120 fps, disque SSD ultra-rapide de 1 To et immersion haptique DualSense.",
        "category": "cat_tech",
        "subcategory": "subcat_gaming",
        "gender": "gender_mixte",
        "ages": ["age_enfant", "age_ado", "age_adulte"],
        "styles": ["style_moderne", "style_tendance"],
        "persos": ["perso_geek", "perso_cool", "perso_fetard"],
        "passions": ["passion_jeuxvideo", "passion_tech"],
        "types": ["type_high_tech", "type_jeux_jouets"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 99,
    },
    {
        "id": "nintendo_switch_oled",
        "name": "Nintendo Switch Modèle OLED Blanc",
        "brand": "Nintendo",
        "price": 319.99,
        "url": "https://www.nintendo.fr/Nintendo-Switch/Nintendo-Switch-Modele-OLED/Nintendo-Switch-Modele-OLED-2000484.html",
        "image": "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=1000&auto=format&fit=crop&q=80",
        "description": "Écran OLED éclatant de 7 pouces, support réglable large et 64 Go de stockage pour jouer partout.",
        "category": "cat_tech",
        "subcategory": "subcat_gaming",
        "gender": "gender_mixte",
        "ages": ["age_enfant", "age_ado", "age_adulte"],
        "styles": ["style_decontracte", "style_moderne"],
        "persos": ["perso_geek", "perso_sociable", "perso_cool"],
        "passions": ["passion_jeuxvideo", "passion_voyages"],
        "types": ["type_high_tech", "type_jeux_jouets"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 98,
    },

    # 1.7 subcat_maison_connectee
    {
        "id": "sonos_era_100",
        "name": "Sonos Era 100 Enceinte Connectée Intelligente",
        "brand": "Sonos",
        "price": 279.0,
        "url": "https://www.sonos.com/fr-fr/shop/era-100",
        "image": "https://images.unsplash.com/photo-1543512214-318c7553f230?w=1000&auto=format&fit=crop&q=80",
        "description": "Acoustique stéréo de nouvelle génération avec connectivité Bluetooth, Wi-Fi et contrôle tactile.",
        "category": "cat_tech",
        "subcategory": "subcat_maison_connectee",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_minimaliste", "style_moderne"],
        "persos": ["perso_zen", "perso_casanier", "perso_techie"],
        "passions": ["passion_musique", "passion_tech"],
        "types": ["type_high_tech", "type_maison_deco"],
        "occasions": ["occasion_cremaillere", "occasion_anniversaire", "occasion_noel"],
        "popularity": 93,
    },
    {
        "id": "philips_hue_starter_kit",
        "name": "Philips Hue Pack de Démarrage 3 Ampoules E27 & Pont",
        "brand": "Philips",
        "price": 149.99,
        "url": "https://www.philips-hue.com/fr-fr",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1000&auto=format&fit=crop&q=80",
        "description": "16 millions de couleurs et synchronisation musicale pour créer des ambiances lumineuses magiques.",
        "category": "cat_tech",
        "subcategory": "subcat_maison_connectee",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_moderne", "style_tendance"],
        "persos": ["perso_creatif", "perso_techie", "perso_casanier"],
        "passions": ["passion_tech", "passion_jeuxvideo", "passion_cinema"],
        "types": ["type_high_tech", "type_maison_deco"],
        "occasions": ["occasion_cremaillere", "occasion_anniversaire"],
        "popularity": 91,
    },

    # 1.8 subcat_gadgets_divers
    {
        "id": "kindle_paperwhite_16go",
        "name": "Kindle Paperwhite 16 Go Écran 6.8\" Sans Reflets",
        "brand": "Amazon",
        "price": 169.99,
        "url": "https://www.amazon.fr/dp/B08N3TCP2F",
        "image": "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=1000&auto=format&fit=crop&q=80",
        "description": "Éclairage chaud réglable, étanchéité IPX8 et jusqu'à 10 semaines d'autonomie pour dévorer des livres.",
        "category": "cat_tech",
        "subcategory": "subcat_gadgets_divers",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_minimaliste", "style_moderne"],
        "persos": ["perso_intellectuel", "perso_zen", "perso_casanier"],
        "passions": ["passion_lecture", "passion_voyages"],
        "types": ["type_high_tech", "type_livres_bd", "type_culture"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_fete"],
        "popularity": 96,
    },
    {
        "id": "apple_airtag_pack_4",
        "name": "Apple AirTag Coffret de 4 Balises Bluetooth",
        "brand": "Apple",
        "price": 129.0,
        "url": "https://www.apple.com/fr/airtag/",
        "image": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=1000&auto=format&fit=crop&q=80",
        "description": "Ne perdez plus jamais vos clés, sacs ou valises grâce au réseau Localiser mondial d'Apple.",
        "category": "cat_tech",
        "subcategory": "subcat_gadgets_divers",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_minimaliste", "style_moderne"],
        "persos": ["perso_pratique", "perso_aventurier", "perso_techie"],
        "passions": ["passion_voyages", "passion_tech"],
        "types": ["type_high_tech", "type_voyage_aventure"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_remerciement"],
        "popularity": 95,
    },

    # =========================================================================
    # 2. MODE (cat_mode)
    # =========================================================================
    # 2.1 subcat_vetements_femme
    {
        "id": "sezane_gaspard_cardigan",
        "name": "Sézane Cardigan Gaspard en Mohair & Alpaga",
        "brand": "Sézane",
        "price": 115.0,
        "url": "https://www.sezane.com/fr/product/gilet-gaspard/",
        "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=1000&auto=format&fit=crop&q=80",
        "description": "L'iconique gilet Sézane d'une douceur infinie avec ses boutons nacrés réversibles.",
        "category": "cat_mode",
        "subcategory": "subcat_vetements_femme",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_elegant", "style_boheme", "style_tendance"],
        "persos": ["perso_fashion", "perso_romantique"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_saint_valentin"],
        "popularity": 98,
    },
    {
        "id": "zara_manteau_laine_oversize",
        "name": "Zara Manteau Long Ceinturé en Drap de Laine",
        "brand": "Zara",
        "price": 149.0,
        "url": "https://www.zara.com/fr/",
        "image": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=1000&auto=format&fit=crop&q=80",
        "description": "Coupe tailoring épurée avec col à revers et ceinture assortie pour une allure résolument moderne.",
        "category": "cat_mode",
        "subcategory": "subcat_vetements_femme",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_elegant", "style_tendance", "style_minimaliste"],
        "persos": ["perso_fashion", "perso_ambitieux"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 92,
    },

    # 2.2 subcat_vetements_homme
    {
        "id": "lacoste_polo_classic_fit",
        "name": "Lacoste Polo Classique L.12.12 en Petit Piqué",
        "brand": "Lacoste",
        "price": 110.0,
        "url": "https://www.lacoste.com/fr/",
        "image": "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=1000&auto=format&fit=crop&q=80",
        "description": "L'incontournable polo inventé par René Lacoste en 1933 avec crocodile brodé sur la poitrine.",
        "category": "cat_mode",
        "subcategory": "subcat_vetements_homme",
        "gender": "gender_homme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_classique", "style_elegant", "style_sportif"],
        "persos": ["perso_actif", "perso_sociable"],
        "passions": ["passion_mode", "passion_sport"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_fete", "occasion_anniversaire", "occasion_noel"],
        "popularity": 96,
    },
    {
        "id": "ralph_lauren_pull_torsade_coton",
        "name": "Polo Ralph Lauren Pull Torsadé en Coton Peigné",
        "brand": "Polo Ralph Lauren",
        "price": 189.0,
        "url": "https://www.ralphlauren.fr/",
        "image": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=1000&auto=format&fit=crop&q=80",
        "description": "Maille torsadée intemporelle ornée du poney brodé contrasté pour une élégance preppy chic.",
        "category": "cat_mode",
        "subcategory": "subcat_vetements_homme",
        "gender": "gender_homme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_classique", "style_elegant", "style_luxe"],
        "persos": ["perso_ambitieux", "perso_sociable"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_fete"],
        "popularity": 94,
    },

    # 2.3 subcat_chaussures
    {
        "id": "nike_air_force_1_07",
        "name": "Nike Air Force 1 '07 Baskets Blanches",
        "brand": "Nike",
        "price": 119.99,
        "url": "https://www.nike.com/fr/t/chaussure-air-force-1-07-wrHXkn",
        "image": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1000&auto=format&fit=crop&q=80",
        "description": "La légende du basketball avec cuir immaculé cousu, amorti Nike Air et semelle en caoutchouc durable.",
        "category": "cat_mode",
        "subcategory": "subcat_chaussures",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_streetwear", "style_tendance", "style_sportif"],
        "persos": ["perso_cool", "perso_actif"],
        "passions": ["passion_mode", "passion_sport"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 99,
    },
    {
        "id": "adidas_samba_og",
        "name": "Adidas Originals Samba OG Baskets Rétro",
        "brand": "Adidas",
        "price": 120.0,
        "url": "https://www.adidas.fr/samba-og",
        "image": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=1000&auto=format&fit=crop&q=80",
        "description": "Le phénomène streetwear avec tige en cuir souple, empiècement suède en T et semelle gomme rétro.",
        "category": "cat_mode",
        "subcategory": "subcat_chaussures",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_tendance", "style_vintage", "style_streetwear"],
        "persos": ["perso_fashion", "perso_cool"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 98,
    },

    # 2.4 subcat_sacs_maroquinerie
    {
        "id": "jacquemus_le_chiquito_moyen",
        "name": "Jacquemus Le Chiquito Moyen Sac Bandoulière Cuir",
        "brand": "Jacquemus",
        "price": 650.0,
        "url": "https://www.jacquemus.com/fr_fr",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1000&auto=format&fit=crop&q=80",
        "description": "Sac en cuir lisse structuré avec anse renforcée, logo doré Jacquemus et bandoulière amovible.",
        "category": "cat_mode",
        "subcategory": "subcat_sacs_maroquinerie",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_tendance", "style_elegant"],
        "persos": ["perso_fashion", "perso_excentrique"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 97,
    },
    {
        "id": "longchamp_le_pliage_original",
        "name": "Longchamp Le Pliage Original Sac Porté Épaule L",
        "brand": "Longchamp",
        "price": 130.0,
        "url": "https://www.longchamp.com/fr/fr/",
        "image": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1000&auto=format&fit=crop&q=80",
        "description": "Inspiré de l'origami, toile nylon ultra-légère et rabat en cuir de Russie reconnaissable entre tous.",
        "category": "cat_mode",
        "subcategory": "subcat_sacs_maroquinerie",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_classique", "style_elegant"],
        "persos": ["perso_pratique", "perso_sociable"],
        "passions": ["passion_mode", "passion_voyages"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_fete", "occasion_anniversaire", "occasion_noel"],
        "popularity": 95,
    },

    # 2.5 subcat_bijoux
    {
        "id": "pandora_bracelet_maille_serpent",
        "name": "Pandora Bracelet Maille Serpent en Argent 925",
        "brand": "Pandora",
        "price": 69.0,
        "url": "https://fr.pandora.net/fr/bracelets/",
        "image": "https://images.unsplash.com/photo-1611591475819-79b8b4a72e31?w=1000&auto=format&fit=crop&q=80",
        "description": "Le bracelet signature Moments à fermoir barillet pour composer et collectionner ses charms préférés.",
        "category": "cat_mode",
        "subcategory": "subcat_bijoux",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_elegant", "style_romantique"],
        "persos": ["perso_romantique", "perso_sociable"],
        "passions": ["passion_mode"],
        "types": ["type_bijoux", "type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_saint_valentin", "occasion_noel", "occasion_fete"],
        "popularity": 97,
    },
    {
        "id": "swarovski_collier_attract_solitaire",
        "name": "Swarovski Collier Solitaire Attract Rond",
        "brand": "Swarovski",
        "price": 85.0,
        "url": "https://www.swarovski.com/fr-FR/",
        "image": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1000&auto=format&fit=crop&q=80",
        "description": "Pendentif en cristal taille brillant serti sur chaîne rhodiée étincelante.",
        "category": "cat_mode",
        "subcategory": "subcat_bijoux",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_elegant", "style_minimaliste"],
        "persos": ["perso_romantique", "perso_fashion"],
        "passions": ["passion_mode"],
        "types": ["type_bijoux", "type_mode_accessoires"],
        "occasions": ["occasion_saint_valentin", "occasion_anniversaire", "occasion_noel"],
        "popularity": 93,
    },

    # 2.6 subcat_montres_classiques
    {
        "id": "tissot_prx_powermatic_80",
        "name": "Tissot PRX Powermatic 80 Montre Automatique",
        "brand": "Tissot",
        "price": 745.0,
        "url": "https://www.tissotwatches.com/fr-fr/",
        "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=1000&auto=format&fit=crop&q=80",
        "description": "Boîtier acier 40mm intégré au style 1978 avec cadran gaufré et réserve de marche phénoménale de 80h.",
        "category": "cat_mode",
        "subcategory": "subcat_montres_classiques",
        "gender": "gender_homme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_vintage", "style_elegant"],
        "persos": ["perso_ambitieux", "perso_cool"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_diplome", "occasion_anniversaire", "occasion_noel", "occasion_mariage"],
        "popularity": 96,
    },
    {
        "id": "daniel_wellington_classic_st_mawes",
        "name": "Daniel Wellington Montre Classic St Mawes Cuir",
        "brand": "Daniel Wellington",
        "price": 199.0,
        "url": "https://www.danielwellington.com/fr/",
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1000&auto=format&fit=crop&q=80",
        "description": "Cadran blanc ultra-plat épuré avec boîtier or rose et bracelet en cuir italien brun véritable.",
        "category": "cat_mode",
        "subcategory": "subcat_montres_classiques",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_minimaliste", "style_classique", "style_elegant"],
        "persos": ["perso_intellectuel", "perso_zen"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_fete", "occasion_diplome"],
        "popularity": 91,
    },

    # 2.7 subcat_accessoires_mode
    {
        "id": "rayban_wayfarer_classic",
        "name": "Ray-Ban Original Wayfarer Classic Lunettes de Soleil",
        "brand": "Ray-Ban",
        "price": 165.0,
        "url": "https://www.ray-ban.com/france/",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=1000&auto=format&fit=crop&q=80",
        "description": "Le modèle de lunettes le plus iconique de l'histoire du cinéma en acétate noir avec verres minéraux G-15.",
        "category": "cat_mode",
        "subcategory": "subcat_accessoires_mode",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_vintage", "style_cool", "style_classique"],
        "persos": ["perso_cool", "perso_sociable", "perso_aventurier"],
        "passions": ["passion_mode", "passion_cinema", "passion_voyages"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_fete"],
        "popularity": 97,
    },
    {
        "id": "acne_studios_toronto_scarf",
        "name": "Acne Studios Écharpe Logo en Laine Vierge",
        "brand": "Acne Studios",
        "price": 260.0,
        "url": "https://www.acnestudios.com/fr/fr/",
        "image": "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=1000&auto=format&fit=crop&q=80",
        "description": "Grande écharpe jacquard en laine d'agneau douce ornée du lettrage contrasté Acne Studios.",
        "category": "cat_mode",
        "subcategory": "subcat_accessoires_mode",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_tendance", "style_minimaliste"],
        "persos": ["perso_fashion", "perso_cool"],
        "passions": ["passion_mode"],
        "types": ["type_mode_accessoires"],
        "occasions": ["occasion_noel", "occasion_anniversaire"],
        "popularity": 94,
    },

    # 2.8 subcat_lingerie_nuit
    {
        "id": "etam_pyjama_soie_long",
        "name": "Etam Ensemble Pyjama Chemisier & Pantalon Satin Soie",
        "brand": "Etam",
        "price": 79.99,
        "url": "https://www.etam.com/",
        "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1000&auto=format&fit=crop&q=80",
        "description": "Coupe fluide délicate avec passepoil contrasté pour des nuits douces et élégantes.",
        "category": "cat_mode",
        "subcategory": "subcat_lingerie_nuit",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_elegant", "style_romantique"],
        "persos": ["perso_zen", "perso_casanier", "perso_romantique"],
        "passions": ["passion_mode", "passion_beaute"],
        "types": ["type_mode_accessoires", "type_bien_etre"],
        "occasions": ["occasion_saint_valentin", "occasion_noel", "occasion_anniversaire"],
        "popularity": 92,
    },

    # =========================================================================
    # 3. MAISON (cat_maison)
    # =========================================================================
    # 3.1 subcat_ambiance_bougies_senteurs
    {
        "id": "diptyque_bougie_baies_190g",
        "name": "Diptyque Bougie Parfumée Baies 190g",
        "brand": "Diptyque",
        "price": 62.0,
        "url": "https://www.diptyqueparis.com/fr_fr/p/bougie-baies-190g.html",
        "image": "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=1000&auto=format&fit=crop&q=80",
        "description": "L'accord irrésistible de baies de cassis mêlées aux accents fleuris de roses fraîches.",
        "category": "cat_maison",
        "subcategory": "subcat_ambiance_bougies_senteurs",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_elegant", "style_minimaliste"],
        "persos": ["perso_zen", "perso_casanier", "perso_romantique"],
        "passions": ["passion_art", "passion_beaute"],
        "types": ["type_maison_deco", "type_bien_etre"],
        "occasions": ["occasion_cremaillere", "occasion_anniversaire", "occasion_noel", "occasion_remerciement"],
        "popularity": 98,
    },
    {
        "id": "baobab_bougie_max_10_totem",
        "name": "Baobab Collection Bougie Max 10 Madagascar Vanilla",
        "brand": "Baobab Collection",
        "price": 115.0,
        "url": "https://www.baobabcollection.com/",
        "image": "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=1000&auto=format&fit=crop&q=80",
        "description": "Verrerie soufflée bouche par des artisans avec cire parfumée d'exception vanille & frangipanier.",
        "category": "cat_maison",
        "subcategory": "subcat_ambiance_bougies_senteurs",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_elegant"],
        "persos": ["perso_epicurien", "perso_zen"],
        "passions": ["passion_art", "passion_voyages"],
        "types": ["type_maison_deco"],
        "occasions": ["occasion_cremaillere", "occasion_anniversaire", "occasion_mariage"],
        "popularity": 93,
    },

    # 3.2 subcat_cuisine_arts_de_la_table
    {
        "id": "le_creuset_cocotte_fonte_24cm",
        "name": "Le Creuset Cocotte Ronde en Fonte Émaillée 24cm Volcanique",
        "brand": "Le Creuset",
        "price": 335.0,
        "url": "https://www.lecreuset.fr/",
        "image": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=1000&auto=format&fit=crop&q=80",
        "description": "Fabriquée en France depuis 1925, l'ustensile culinaire indispensable pour des mijotés d'exception.",
        "category": "cat_maison",
        "subcategory": "subcat_cuisine_arts_de_la_table",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_classique", "style_luxe", "style_vintage"],
        "persos": ["perso_epicurien", "perso_gourmand", "perso_casanier"],
        "passions": ["passion_cuisine", "passion_vins"],
        "types": ["type_maison_deco", "type_gastronomie"],
        "occasions": ["occasion_mariage", "occasion_cremaillere", "occasion_noel", "occasion_anniversaire"],
        "popularity": 97,
    },
    {
        "id": "global_couteau_chef_g2",
        "name": "Global Couteau de Chef Japonais G-2 Lame 20cm",
        "brand": "Global",
        "price": 139.0,
        "url": "https://www.global-knife.com/",
        "image": "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=1000&auto=format&fit=crop&q=80",
        "description": "Acier inoxydable Cromova 18 forgé monobloc avec manche pointillé pour un tranchant légendaire.",
        "category": "cat_maison",
        "subcategory": "subcat_cuisine_arts_de_la_table",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_minimaliste", "style_moderne"],
        "persos": ["perso_epicurien", "perso_gourmand", "perso_pratique"],
        "passions": ["passion_cuisine"],
        "types": ["type_maison_deco", "type_gastronomie"],
        "occasions": ["occasion_anniversaire", "occasion_cremaillere", "occasion_fete"],
        "popularity": 94,
    },

    # 3.3 subcat_electromenager
    {
        "id": "kitchenaid_artisan_robot_patissier",
        "name": "KitchenAid Robot Pâtissier Multifonction Artisan 4.8L",
        "brand": "KitchenAid",
        "price": 649.0,
        "url": "https://www.kitchenaid.fr/",
        "image": "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=1000&auto=format&fit=crop&q=80",
        "description": "Mouvement planétaire d'exception avec corps tout en métal coulé et bol en acier inoxydable.",
        "category": "cat_maison",
        "subcategory": "subcat_electromenager",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_vintage", "style_luxe"],
        "persos": ["perso_gourmand", "perso_creatif", "perso_epicurien"],
        "passions": ["passion_cuisine"],
        "types": ["type_maison_deco", "type_gastronomie"],
        "occasions": ["occasion_mariage", "occasion_anniversaire", "occasion_noel"],
        "popularity": 98,
    },
    {
        "id": "smeg_bouilloire_annees_50",
        "name": "Smeg Bouilloire Électrique Années 50 Crème",
        "brand": "Smeg",
        "price": 169.0,
        "url": "https://www.smeg.fr/",
        "image": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=1000&auto=format&fit=crop&q=80",
        "description": "Design rétro inimitable en acier inox avec ouverture douce du couvercle et base pivotante 360°.",
        "category": "cat_maison",
        "subcategory": "subcat_electromenager",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_vintage", "style_elegant"],
        "persos": ["perso_epicurien", "perso_casanier"],
        "passions": ["passion_cuisine", "passion_art"],
        "types": ["type_maison_deco"],
        "occasions": ["occasion_cremaillere", "occasion_anniversaire", "occasion_noel"],
        "popularity": 95,
    },

    # 3.4 subcat_deco_murale_objets
    {
        "id": "ikea_vase_cylindrique_verre",
        "name": "IKEA Lot de 3 Vases en Verre Soufflé Épuré",
        "brand": "IKEA",
        "price": 19.99,
        "url": "https://www.ikea.com/fr/fr/",
        "image": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1000&auto=format&fit=crop&q=80",
        "description": "Lignes scandinaves minimalistes pour mettre en valeur fleurs fraîches ou séchées.",
        "category": "cat_maison",
        "subcategory": "subcat_deco_murale_objets",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_minimaliste", "style_boheme", "style_eco_responsable"],
        "persos": ["perso_zen", "perso_creatif", "perso_casanier"],
        "passions": ["passion_art", "passion_jardinage"],
        "types": ["type_maison_deco"],
        "occasions": ["occasion_cremaillere", "occasion_remerciement", "occasion_anniversaire"],
        "popularity": 89,
    },

    # 3.5 subcat_linge_maison
    {
        "id": "bonsoirs_parure_lit_gaze_coton",
        "name": "Bonsoirs Parure de Lit en Double Gaze de Coton Bio",
        "brand": "Bonsoirs",
        "price": 175.0,
        "url": "https://www.bonsoirs.com/",
        "image": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1000&auto=format&fit=crop&q=80",
        "description": "Lavage stonewashed pour une texture aérienne gaufrée ultra douce qui ne se repasse jamais.",
        "category": "cat_maison",
        "subcategory": "subcat_linge_maison",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_boheme", "style_minimaliste", "style_eco_responsable"],
        "persos": ["perso_zen", "perso_casanier"],
        "passions": ["passion_art", "passion_nature"],
        "types": ["type_maison_deco", "type_bien_etre"],
        "occasions": ["occasion_cremaillere", "occasion_mariage", "occasion_noel"],
        "popularity": 93,
    },

    # 3.6 subcat_rangement_organisation
    {
        "id": "stackers_boite_a_bijoux_cuir",
        "name": "Stackers Grande Boîte à Bijoux Modulaire en Cuir Végétal",
        "brand": "Stackers",
        "price": 89.0,
        "url": "https://stackers.com/",
        "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1000&auto=format&fit=crop&q=80",
        "description": "Système d'étages superposables doublé de velours protecteur pour ranger montres et parures.",
        "category": "cat_maison",
        "subcategory": "subcat_rangement_organisation",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_elegant", "style_minimaliste"],
        "persos": ["perso_pratique", "perso_fashion"],
        "passions": ["passion_mode"],
        "types": ["type_maison_deco", "type_bijoux"],
        "occasions": ["occasion_anniversaire", "occasion_fete", "occasion_noel"],
        "popularity": 91,
    },

    # 3.7 subcat_jardin_exterieur
    {
        "id": "la_siesta_hamac_double_coton",
        "name": "La Siesta Hamac Double Brisa Résistant aux Intempéries",
        "brand": "La Siesta",
        "price": 109.90,
        "url": "https://www.lasiesta.com/fr/",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1000&auto=format&fit=crop&q=80",
        "description": "Tissé à la main en Colombie avec fibres extérieures douces pour des siestes en apesanteur au jardin.",
        "category": "cat_maison",
        "subcategory": "subcat_jardin_exterieur",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_boheme", "style_decontracte"],
        "persos": ["perso_zen", "perso_nature", "perso_aventurier"],
        "passions": ["passion_nature", "passion_jardinage", "passion_voyages"],
        "types": ["type_maison_deco", "type_sport_outdoor"],
        "occasions": ["occasion_anniversaire", "occasion_cremaillere"],
        "popularity": 88,
    },

    # =========================================================================
    # 4. BEAUTÉ (cat_beaute)
    # =========================================================================
    # 4.1 subcat_parfum
    {
        "id": "dior_sauvage_eau_de_parfum",
        "name": "Dior Sauvage Eau de Parfum 100ml",
        "brand": "Dior",
        "price": 142.0,
        "url": "https://www.dior.com/fr_fr/beauty/products/sauvage-eau-de-parfum",
        "image": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=1000&auto=format&fit=crop&q=80",
        "description": "Sillage boisé et ambré puissant enveloppé par la fraîcheur juteuse de la bergamote de Calabre.",
        "category": "cat_beaute",
        "subcategory": "subcat_parfum",
        "gender": "gender_homme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_elegant", "style_moderne"],
        "persos": ["perso_ambitieux", "perso_cool", "perso_sociable"],
        "passions": ["passion_mode", "passion_beaute"],
        "types": ["type_beaute_soins"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_saint_valentin", "occasion_fete"],
        "popularity": 99,
    },
    {
        "id": "chanel_coco_mademoiselle",
        "name": "Chanel Coco Mademoiselle Eau de Parfum 50ml",
        "brand": "Chanel",
        "price": 118.0,
        "url": "https://www.chanel.com/fr/parfums/p/116520/coco-mademoiselle-eau-de-parfum-vaporisateur/",
        "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=1000&auto=format&fit=crop&q=80",
        "description": "L'essence d'une femme libre et audacieuse, oriental féminin aux accords frais d'orange et de patchouli.",
        "category": "cat_beaute",
        "subcategory": "subcat_parfum",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_elegant"],
        "persos": ["perso_romantique", "perso_fashion"],
        "passions": ["passion_mode", "passion_beaute"],
        "types": ["type_beaute_soins"],
        "occasions": ["occasion_anniversaire", "occasion_saint_valentin", "occasion_noel", "occasion_fete"],
        "popularity": 98,
    },

    # 4.2 subcat_soin_visage
    {
        "id": "the_ordinary_hyaluronic_acid_b5",
        "name": "The Ordinary Acide Hyaluronique 2% + B5 Sérum 60ml",
        "brand": "The Ordinary",
        "price": 17.90,
        "url": "https://theordinary.com/fr-fr",
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=1000&auto=format&fit=crop&q=80",
        "description": "Hydratation multi-profondeur repulpante sans huile pour un éclat cutané immédiat.",
        "category": "cat_beaute",
        "subcategory": "subcat_soin_visage",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_minimaliste", "style_moderne"],
        "persos": ["perso_pratique", "perso_zen"],
        "passions": ["passion_beaute"],
        "types": ["type_beaute_soins", "type_bien_etre"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_remerciement"],
        "popularity": 96,
    },
    {
        "id": "kiehls_ultra_facial_cream",
        "name": "Kiehl's Ultra Facial Cream Crème Hydratante 24h 50ml",
        "brand": "Kiehl's",
        "price": 38.0,
        "url": "https://www.kiehls.fr/",
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1000&auto=format&fit=crop&q=80",
        "description": "Formulée à base de squalane et glycoprotéine glaciaire pour fortifier la barrière cutanée.",
        "category": "cat_beaute",
        "subcategory": "subcat_soin_visage",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_elegant"],
        "persos": ["perso_zen", "perso_actif"],
        "passions": ["passion_beaute"],
        "types": ["type_beaute_soins"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 93,
    },

    # 4.3 subcat_soin_corps
    {
        "id": "rituals_sakura_body_cream",
        "name": "Rituals The Ritual of Sakura Crème pour le Corps 220ml",
        "brand": "Rituals",
        "price": 20.90,
        "url": "https://www.rituals.com/fr-fr/",
        "image": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=1000&auto=format&fit=crop&q=80",
        "description": "Fleurs de cerisier et lait de riz biologique pour nourrir intensément et parfumer la peau.",
        "category": "cat_beaute",
        "subcategory": "subcat_soin_corps",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_zen", "style_elegant"],
        "persos": ["perso_zen", "perso_romantique"],
        "passions": ["passion_beaute"],
        "types": ["type_beaute_soins", "type_bien_etre"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_remerciement"],
        "popularity": 95,
    },

    # 4.4 subcat_maquillage
    {
        "id": "charlotte_tilbury_pillow_talk_lipstick",
        "name": "Charlotte Tilbury Matte Revolution Rouge à Lèvres Pillow Talk",
        "brand": "Charlotte Tilbury",
        "price": 36.0,
        "url": "https://www.charlottetilbury.com/fr/",
        "image": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=1000&auto=format&fit=crop&q=80",
        "description": "La nuance nude universelle primée aux pigments lumineux 3D pour des lèvres douces et galbées.",
        "category": "cat_beaute",
        "subcategory": "subcat_maquillage",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_tendance", "style_elegant"],
        "persos": ["perso_fashion", "perso_romantique"],
        "passions": ["passion_beaute", "passion_mode"],
        "types": ["type_beaute_soins"],
        "occasions": ["occasion_anniversaire", "occasion_saint_valentin", "occasion_noel"],
        "popularity": 97,
    },

    # 4.5 subcat_cheveux_coiffure
    {
        "id": "ghd_gold_styler",
        "name": "ghd Gold Lisseur Professionnel Technologie Dual-Zone",
        "brand": "ghd",
        "price": 239.0,
        "url": "https://www.ghdhair.com/fr/",
        "image": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1000&auto=format&fit=crop&q=80",
        "description": "Température optimale de coiffage de 185°C pour des cheveux plus lisses, soyeux et protégés.",
        "category": "cat_beaute",
        "subcategory": "subcat_cheveux_coiffure",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_moderne"],
        "persos": ["perso_fashion", "perso_ambitieux"],
        "passions": ["passion_beaute", "passion_mode"],
        "types": ["type_beaute_soins", "type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 96,
    },

    # 4.6 subcat_rasage_barbe
    {
        "id": "philips_oneblade_pro_360",
        "name": "Philips OneBlade Pro 360 Visage & Corps Tondeuse Hybride",
        "brand": "Philips",
        "price": 79.99,
        "url": "https://www.philips.fr/c-m-pe/oneblade-taillez-r想ez-stylisez",
        "image": "https://images.unsplash.com/photo-1621607512214-68297480165e?w=1000&auto=format&fit=crop&q=80",
        "description": "Lame 360 innovante qui pivote dans toutes les directions pour tailler, styliser et raser à n'importe quelle longueur.",
        "category": "cat_beaute",
        "subcategory": "subcat_rasage_barbe",
        "gender": "gender_homme",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_pratique"],
        "persos": ["perso_pratique", "perso_cool"],
        "passions": ["passion_beaute"],
        "types": ["type_beaute_soins"],
        "occasions": ["occasion_anniversaire", "occasion_fete", "occasion_noel"],
        "popularity": 98,
    },

    # 4.7 subcat_bienetre_spa
    {
        "id": "rituals_hammam_gift_set_l",
        "name": "Rituals Coffret Cadeau Grand Format The Ritual of Hammam",
        "brand": "Rituals",
        "price": 54.90,
        "url": "https://www.rituals.com/fr-fr/gift-sets",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1000&auto=format&fit=crop&q=80",
        "description": "Eucalyptus rafraîchissant et huile d'argan pour recréer une cérémonie de spa purifiante à la maison.",
        "category": "cat_beaute",
        "subcategory": "subcat_bienetre_spa",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_zen", "style_luxe"],
        "persos": ["perso_zen", "perso_epicurien"],
        "passions": ["passion_beaute", "passion_yoga"],
        "types": ["type_bien_etre", "type_beaute_soins"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_remerciement"],
        "popularity": 95,
    },

    # 4.8 subcat_appareils_beaute
    {
        "id": "dyson_airwrap_multi_styler",
        "name": "Dyson Airwrap Multi-Styler Complete Long Cuivre & Nickel",
        "brand": "Dyson",
        "price": 549.0,
        "url": "https://www.dyson.fr/soin-des-cheveux/dyson-airwrap/complete-long-cuivre-nickel",
        "image": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1000&auto=format&fit=crop&q=80",
        "description": "Boucle, ondule, lisse et sèche sans chaleur extrême grâce à l'effet aérodynamique Coanda.",
        "category": "cat_beaute",
        "subcategory": "subcat_appareils_beaute",
        "gender": "gender_femme",
        "ages": ["age_ado", "age_adulte"],
        "styles": ["style_luxe", "style_moderne"],
        "persos": ["perso_fashion", "perso_ambitieux"],
        "passions": ["passion_beaute", "passion_mode", "passion_tech"],
        "types": ["type_beaute_soins", "type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel", "occasion_diplome"],
        "popularity": 99,
    },

    # =========================================================================
    # 5. FOOD & GASTRONOMIE (cat_food)
    # =========================================================================
    # 5.1 subcat_chocolats_confiseries
    {
        "id": "pierre_herme_macarons_infiniment",
        "name": "Pierre Hermé Coffret 18 Macarons Signatures d'Exception",
        "brand": "Pierre Hermé",
        "price": 62.0,
        "url": "https://www.pierreherme.com/",
        "image": "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=1000&auto=format&fit=crop&q=80",
        "description": "L'Ispahan rose-framboise-litchi et les créations chocolatées du meilleur pâtissier du monde.",
        "category": "cat_food",
        "subcategory": "subcat_chocolats_confiseries",
        "gender": "gender_mixte",
        "ages": ["age_enfant", "age_ado", "age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_gourmand", "style_elegant"],
        "persos": ["perso_gourmand", "perso_epicurien", "perso_romantique"],
        "passions": ["passion_cuisine", "passion_art"],
        "types": ["type_gastronomie"],
        "occasions": ["occasion_anniversaire", "occasion_saint_valentin", "occasion_noel", "occasion_remerciement"],
        "popularity": 99,
    },
    {
        "id": "maison_du_chocolat_coffret_pralines",
        "name": "La Maison du Chocolat Coffret Maison Écrin 40 Pièces",
        "brand": "La Maison du Chocolat",
        "price": 49.0,
        "url": "https://www.lamaisonduchocolat.com/fr_fr/",
        "image": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=1000&auto=format&fit=crop&q=80",
        "description": "Ganaches soyeuses et pralinés fondants nés du savoir-faire artisanal de Nicolas Cloiseau.",
        "category": "cat_food",
        "subcategory": "subcat_chocolats_confiseries",
        "gender": "gender_mixte",
        "ages": ["age_enfant", "age_ado", "age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_classique"],
        "persos": ["perso_gourmand", "perso_epicurien"],
        "passions": ["passion_cuisine"],
        "types": ["type_gastronomie"],
        "occasions": ["occasion_noel", "occasion_anniversaire", "occasion_fete"],
        "popularity": 96,
    },

    # 5.2 subcat_vins_spiritueux
    {
        "id": "moet_chandon_brut_imperial",
        "name": "Champagne Moët & Chandon Brut Impérial Étui Cadeau 75cl",
        "brand": "Moët & Chandon",
        "price": 54.0,
        "url": "https://www.moet.com/fr-fr",
        "image": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1000&auto=format&fit=crop&q=80",
        "description": "Le champagne iconique depuis 1869, éclat fruité avec un palais savoureux et une maturité élégante.",
        "category": "cat_food",
        "subcategory": "subcat_vins_spiritueux",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_festif", "style_elegant"],
        "persos": ["perso_fetard", "perso_sociable", "perso_epicurien"],
        "passions": ["passion_vins", "passion_cuisine"],
        "types": ["type_gastronomie"],
        "occasions": ["occasion_mariage", "occasion_anniversaire", "occasion_cremaillere", "occasion_diplome", "occasion_noel"],
        "popularity": 98,
    },
    {
        "id": "veuve_clicquot_brut_carte_jaune",
        "name": "Champagne Veuve Clicquot Brut Carte Jaune 75cl",
        "brand": "Veuve Clicquot",
        "price": 58.0,
        "url": "https://www.veuveclicquot.com/fr-fr",
        "image": "https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=1000&auto=format&fit=crop&q=80",
        "description": "La force du Pinot Noir sublimée par la fraîcheur du Chardonnay pour une dégustation inoubliable.",
        "category": "cat_food",
        "subcategory": "subcat_vins_spiritueux",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_festif"],
        "persos": ["perso_fetard", "perso_epicurien"],
        "passions": ["passion_vins"],
        "types": ["type_gastronomie"],
        "occasions": ["occasion_anniversaire", "occasion_mariage", "occasion_noel"],
        "popularity": 97,
    },

    # 5.3 subcat_cafe_the
    {
        "id": "kusmi_tea_coffret_iconiques",
        "name": "Kusmi Tea Coffret Les Iconiques 24 Sachets Bio",
        "brand": "Kusmi Tea",
        "price": 23.90,
        "url": "https://www.kusmitea.com/fr/",
        "image": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=1000&auto=format&fit=crop&q=80",
        "description": "Assortiment de 6 thés et infusions bio emblématiques dont Anastasia, Prince Vladimir et AquaRosa.",
        "category": "cat_food",
        "subcategory": "subcat_cafe_the",
        "gender": "gender_mixte",
        "ages": ["age_ado", "age_adulte", "age_senior"],
        "styles": ["style_zen", "style_eco_responsable", "style_elegant"],
        "persos": ["perso_zen", "perso_casanier", "perso_intellectuel"],
        "passions": ["passion_cuisine", "passion_yoga", "passion_lecture"],
        "types": ["type_gastronomie", "type_bien_etre"],
        "occasions": ["occasion_remerciement", "occasion_anniversaire", "occasion_noel", "occasion_fete"],
        "popularity": 96,
    },
    {
        "id": "nespresso_coffret_decouverte_100",
        "name": "Nespresso Coffret Assortiment 100 Capsules Grands Crus",
        "brand": "Nespresso",
        "price": 49.50,
        "url": "https://www.nespresso.com/fr/fr/",
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=1000&auto=format&fit=crop&q=80",
        "description": "Une palette d'arômes d'exception d'espressos et lungos torréfiés avec soin.",
        "category": "cat_food",
        "subcategory": "subcat_cafe_the",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_moderne", "style_luxe"],
        "persos": ["perso_epicurien", "perso_pratique", "perso_ambitieux"],
        "passions": ["passion_cuisine"],
        "types": ["type_gastronomie"],
        "occasions": ["occasion_cremaillere", "occasion_remerciement", "occasion_noel"],
        "popularity": 94,
    },

    # 5.4 subcat_epicerie_fine
    {
        "id": "fauchon_coffret_prestige_terroir",
        "name": "Fauchon Coffret Gourmand L'Iconique Parisien",
        "brand": "Fauchon",
        "price": 95.0,
        "url": "https://www.fauchon.com/",
        "image": "https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=1000&auto=format&fit=crop&q=80",
        "description": "Foie gras de canard entier, confit de figues, rillettes pur canard et toasts artisanaux dans un coffret signature.",
        "category": "cat_food",
        "subcategory": "subcat_epicerie_fine",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_luxe", "style_gourmand", "style_classique"],
        "persos": ["perso_epicurien", "perso_gourmand", "perso_sociable"],
        "passions": ["passion_cuisine", "passion_vins"],
        "types": ["type_gastronomie"],
        "occasions": ["occasion_noel", "occasion_anniversaire", "occasion_remerciement", "occasion_fete"],
        "popularity": 97,
    },

    # 5.5 subcat_coffrets_degustation
    {
        "id": "le_petit_ballon_coffret_sommelier",
        "name": "Le Petit Ballon Coffret Dégustation 3 Bouteilles Pépites & Guide",
        "brand": "Le Petit Ballon",
        "price": 59.90,
        "url": "https://www.lepetitballon.com/",
        "image": "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1000&auto=format&fit=crop&q=80",
        "description": "Sélectionnée par Jean-Michel Deluc, ancien chef sommelier du Ritz avec fiches accords mets-vins.",
        "category": "cat_food",
        "subcategory": "subcat_coffrets_degustation",
        "gender": "gender_mixte",
        "ages": ["age_adulte", "age_senior"],
        "styles": ["style_epicurien", "style_elegant"],
        "persos": ["perso_epicurien", "perso_sociable"],
        "passions": ["passion_vins", "passion_cuisine"],
        "types": ["type_gastronomie"],
        "occasions": ["occasion_anniversaire", "occasion_cremaillere", "occasion_noel", "occasion_fete"],
        "popularity": 95,
    },

    # =========================================================================
    # 6. JEUX, CULTURE & LOISIRS
    # =========================================================================
    {
        "id": "lego_faucon_millenium_star_wars",
        "name": "LEGO Star Wars Faucon Millennium 75257",
        "brand": "LEGO",
        "price": 169.99,
        "url": "https://www.lego.com/fr-fr/product/millennium-falcon-75257",
        "image": "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=1000&auto=format&fit=crop&q=80",
        "description": "1351 pièces pour assembler le vaisseau légendaire avec tourelles rotatives, 7 figurines et intérieur détaillé.",
        "category": "cat_tech",
        "subcategory": "subcat_gaming",
        "gender": "gender_mixte",
        "ages": ["age_enfant", "age_ado", "age_adulte"],
        "styles": ["style_creatif", "style_geek", "style_tendance"],
        "persos": ["perso_geek", "perso_creatif", "perso_casanier"],
        "passions": ["passion_jeuxvideo", "passion_cinema", "passion_loisirs_creatifs"],
        "types": ["type_jeux_jouets", "type_culture", "type_high_tech"],
        "occasions": ["occasion_anniversaire", "occasion_noel"],
        "popularity": 99,
    },
]

def format_product(raw: dict) -> dict:
    price = float(raw["price"])
    budget_tag = get_budget_tag(price)
    
    cat = raw["category"]
    subcat = raw["subcategory"]
    gender = raw["gender"]
    
    tags = [
        gender,
        cat,
        subcat,
        budget_tag,
    ]
    
    for a in raw.get("ages", []):
        tags.append(a)
    for s in raw.get("styles", []):
        tags.append(s)
    for p in raw.get("persos", []):
        tags.append(p)
    for pa in raw.get("passions", []):
        tags.append(pa)
    for t in raw.get("types", []):
        tags.append(t)
    for o in raw.get("occasions", []):
        tags.append(o)
    
    popularity = raw.get("popularity", 90)
    if popularity >= 95:
        tags.append("popularite_5")
    elif popularity >= 85:
        tags.append("popularite_4")
    else:
        tags.append("popularite_3")
        
    keywords = [
        raw["brand"].lower(),
        raw["name"].lower(),
        cat.replace("cat_", ""),
        subcat.replace("subcat_", "").replace("_", " "),
        "cadeau",
    ]
    
    words = re.findall(r"\w+", raw["name"].lower())
    for w in words:
        if len(w) > 2 and w not in keywords:
            keywords.append(w)
            
    # Structure unifiée compatible Firestore + Flutter
    return {
        "id": raw["id"],
        "name": raw["name"],
        "product_title": raw["name"],
        "title": raw["name"],
        "brand": raw["brand"],
        "price": price,
        "product_price": f"{price:.2f} €",
        "url": raw["url"],
        "product_url": raw["url"],
        "buyUrl": raw["url"],
        "image": raw["image"],
        "product_photo": raw["image"],
        "imageUrl": raw["image"],
        "description": raw["description"],
        "category": cat,
        "subcategory": subcat,
        "categories": [cat, subcat, raw["brand"].lower()],
        "subcategories": [subcat],
        "tags": list(dict.fromkeys(tags)),
        "keywords": list(dict.fromkeys(keywords)),
        "popularity": popularity,
        "active": True,
        "source": "doron_luxury_catalog",
    }

def main():
    formatted_products = [format_product(p) for p in PRODUCTS_DATA]
    
    print(f"📦 Total fiches produits formatées : {len(formatted_products)}")
    
    FALLBACK_JSON.parent.mkdir(parents=True, exist_ok=True)
    with FALLBACK_JSON.open("w", encoding="utf-8") as f:
        json.dump(formatted_products, f, indent=2, ensure_ascii=False)
    print(f"✅ Écrit dans {FALLBACK_JSON.relative_to(BASE_DIR)}")
    
    PIPELINE_JSON.parent.mkdir(parents=True, exist_ok=True)
    with PIPELINE_JSON.open("w", encoding="utf-8") as f:
        json.dump(formatted_products, f, indent=2, ensure_ascii=False)
    print(f"✅ Écrit dans {PIPELINE_JSON.relative_to(BASE_DIR)}")

if __name__ == "__main__":
    main()
